const CHANNELS=['Chaco-Corrientes','Rosario','Amistades','Musica','Religion','IA','Gay','Parejas'];
const $=s=>document.querySelector(s), socket=io({autoConnect:false});
let me=null,current={type:'channel',id:CHANNELS[0]},users=[],hist={},unread={},pendingImage=null,credentials=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=()=>current.type==='channel'?`c:${current.id}`:`p:${current.id}`;
function fillChannels(){['#initialChannel','#mobileChannel','#desktopChannel'].forEach(sel=>$(sel).innerHTML=CHANNELS.map(c=>`<option value="${c}"># ${c}</option>`).join(''));}
fillChannels();
$('#loginForm').onsubmit=e=>{e.preventDefault();credentials={nick:$('#nick').value,channel:$('#initialChannel').value,color:'#'+Math.floor(Math.random()*0x999999+0x333333).toString(16).slice(0,6)};socket.connect();};
socket.on('connect',()=>{if(credentials){credentials.channel=current.id;socket.emit('join',credentials)}});
socket.on('joined',d=>{me=d;current={type:'channel',id:d.channel};$('#login').classList.add('hidden');$('#app').classList.remove('hidden');renderAll();});
socket.on('connect_error',e=>$('#loginError').textContent=e.message);socket.on('errorMessage',x=>alert(x));socket.on('banned',d=>alert(`Has sido expulsado por usar una palabra prohibida. Baneo: ${d.minutes} minutos.`));
socket.on('channelChanged',d=>{me.channel=d.channel;current={type:'channel',id:d.channel};$('#mobileChannel').value=d.channel;$('#desktopChannel').value=d.channel;closeSheet();renderAll();});
socket.on('users',list=>{users=list;renderLists();});
socket.on('system',m=>{push(`c:${m.channel}`,{...m,system:true});});
socket.on('channelMessage',m=>push(`c:${m.channel}`,m));
socket.on('privateMessage',m=>{const peer=m.fromId===me.id?m.toId:m.fromId,k=`p:${peer}`;push(k,m);if(!(current.type==='private'&&current.id===peer)&&m.fromId!==me.id)unread[peer]=(unread[peer]||0)+1;renderLists();});
socket.on('userLeft',u=>{Object.keys(hist).filter(k=>k===`p:${u.id}`).forEach(k=>hist[k].push({system:true,text:`⬅️ ${u.nick} ha abandonado la sala.`,time:Date.now()}));renderMessages();});
function push(k,m){(hist[k]??=[]).push(m);if(k===key())renderMessages();}
function switchChannel(c){if(me.channel===c){current={type:'channel',id:c};closeSheet();renderAll();return}socket.emit('switchChannel',c);}
function openPrivate(id){if(id===me.id)return;current={type:'private',id};unread[id]=0;closeSheet();renderAll();}
function renderAll(){renderHeader();renderLists();renderMessages();}
function renderHeader(){if(current.type==='channel'){$('#title').textContent='# '+current.id;$('#subtitle').textContent='Sala general';$('#mobileChannel').value=current.id}else{const u=users.find(x=>x.id===current.id);$('#title').textContent=u?.nick||'Chat privado';$('#subtitle').textContent='Conversación privada'}}
function renderLists(){$('#desktopChannel').value=me?.channel||current.id;const userHTML=users.filter(u=>u.id!==me?.id).map(u=>`<button class="listBtn" data-user="${u.id}"><i class="dot"></i><span style="color:${u.color}">${esc(u.nick)}</span>${unread[u.id]?`<b class="badge">${unread[u.id]} msj</b>`:''}</button>`).join('')||'<p>No hay otros usuarios.</p>';const chats=Object.keys(hist).filter(k=>k.startsWith('p:')).map(k=>{const id=k.slice(2),u=users.find(x=>x.id===id),last=hist[k].find(x=>x.nick);return `<button class="listBtn" data-user="${id}">${esc(u?.nick||last?.nick||'Usuario')}${unread[id]?`<b class="badge">${unread[id]}</b>`:''}</button>`}).join('')||'<p>Sin conversaciones.</p>';$('#users').innerHTML=$('#mobileUsers').innerHTML=userHTML;$('#chats').innerHTML=$('#mobileChats').innerHTML=chats;$('#totalUnread').textContent=Object.values(unread).reduce((a,b)=>a+b,0);document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>openPrivate(b.dataset.user));}
function renderMessages(){const list=hist[key()]||[];$('#messages').innerHTML=list.map(m=>{if(m.system)return `<p class="system">${esc(m.text)}</p>`;const own=m.fromId===me.id;return `<div class="msg bubble ${own?'mine':''}"><span class="nick" data-user="${m.fromId}" style="color:${m.color}">${esc(m.nick)}</span>${m.text?`: <i>${esc(m.text)}</i>`:''}${m.image?`<a class="imageLink" href="${m.image}" target="_blank" rel="noopener">🖼️ Ver imagen</a>`:''}<span class="time">${new Date(m.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div>`}).join('');$('#messages').querySelectorAll('.nick[data-user]').forEach(n=>n.onclick=()=>openPrivate(n.dataset.user));$('#messages').scrollTop=$('#messages').scrollHeight;}
$('#desktopChannel').onchange=e=>switchChannel(e.target.value);$('#mobileChannel').onchange=e=>switchChannel(e.target.value);$('#publicRoom').onclick=()=>switchChannel(me.channel);
$('#image').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!/^image\/(png|jpeg|gif|webp)$/.test(f.type)||f.size>5*1024*1024){alert('Solo JPG, PNG, GIF o WEBP de hasta 5 MB.');e.target.value='';return}const r=new FileReader();r.onload=()=>pendingImage=r.result;r.readAsDataURL(f)};
$('#composer').onsubmit=e=>{e.preventDefault();const text=$('#text').value.trim();if(!text&&!pendingImage)return;const data={text,image:pendingImage};socket.emit(current.type==='channel'?'channelMessage':'privateMessage',current.type==='channel'?data:{...data,to:current.id});$('#text').value='';$('#image').value='';pendingImage=null};
function openSheet(){ $('#backdrop').hidden=false;$('#sheet').classList.add('open');$('#sheet').setAttribute('aria-hidden','false'); }function closeSheet(){$('#sheet').classList.remove('open');$('#sheet').setAttribute('aria-hidden','true');$('#backdrop').hidden=true;}
$('#mobileBar').onclick=openSheet;$('#peopleBtn').onclick=openSheet;$('#closeSheet').onclick=closeSheet;$('#backdrop').onclick=closeSheet;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.mobileList').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
