const rooms=[
 {slug:'chat-chaco-corrientes',name:'Chaco y Corrientes',short:'Chaco-Corrientes',title:'Chat de Chaco y Corrientes gratis',description:'Conversá con personas de Resistencia, Corrientes Capital y todo el nordeste argentino en nuestro chat gratuito.',places:'Resistencia, Barranqueras, Sáenz Peña, Corrientes Capital, Goya, Paso de los Libres y otras localidades del NEA'},
 {slug:'chat-rosario',name:'Rosario',short:'Rosario',title:'Chat de Rosario gratis',description:'Entrá al chat de Rosario para conversar, hacer amistades y conocer personas de la ciudad y sus alrededores.',places:'Rosario, Funes, Granadero Baigorria, Villa Gobernador Gálvez y localidades cercanas'},
 {slug:'chat-amistades',name:'Amistades',short:'Amistades',title:'Chat de amistades en Argentina',description:'Un espacio gratuito para conversar, conocer gente y hacer nuevas amistades desde el celular o la computadora.',places:'personas de distintas provincias y ciudades de Argentina'},
 {slug:'chat-musica',name:'Música',short:'Musica',title:'Chat de música en español',description:'Compartí artistas, canciones, recitales y gustos musicales con otras personas en una sala de conversación gratuita.',places:'aficionados al rock, pop, folclore, cumbia, tango y muchos otros estilos'},
 {slug:'chat-religion',name:'Religión',short:'Religion',title:'Chat de religión y espiritualidad',description:'Sala de conversación respetuosa sobre religión, fe y espiritualidad. Participación gratuita.',places:'personas interesadas en conversar con respeto sobre creencias y espiritualidad'},
 {slug:'chat-inteligencia-artificial',name:'Inteligencia Artificial',short:'IA',title:'Chat de inteligencia artificial en español',description:'Conversá sobre inteligencia artificial, herramientas, novedades y aprendizaje con la comunidad.',places:'estudiantes, profesionales, curiosos y usuarios de herramientas de inteligencia artificial'},
 {slug:'chat-gay',name:'Comunidad gay',short:'Gay',title:'Chat gay de Argentina',description:'Espacio de conversación y amistades para la comunidad gay argentina, con acceso gratuito y normas de respeto.',places:'personas de la comunidad de distintas ciudades argentinas'},
 {slug:'chat-parejas',name:'Parejas',short:'Parejas',title:'Chat para conocer gente y parejas',description:'Conversá y conocé personas interesadas en amistades y relaciones dentro de una comunidad moderada.',places:'personas adultas interesadas en conversar y establecer nuevos vínculos'}
];
function layout({siteUrl,title,description,canonical,body,schema}){return `<!doctype html><html lang="es-AR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="${siteUrl}${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="es_AR"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${siteUrl}${canonical}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/seo.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body><header class="top"><a class="brand" href="/">Comunidad Chat</a><nav><a href="#salas">Salas</a><a href="#normas">Normas</a><a class="navCta" href="/chat">Entrar</a></nav></header>${body}<footer><p>Comunidad Chat · Conversaciones gratuitas en español</p><p><a href="/">Inicio</a> · <a href="#normas">Normas y seguridad</a></p></footer></body></html>`}
function cards(){return rooms.map(r=>`<a class="roomCard" href="/salas/${r.slug}"><span># ${r.short}</span><small>${r.description}</small></a>`).join('')}
function renderHome(siteUrl){const title='Chat gratis de Argentina | Salas por ciudad y temas',description='Comunidad de chat gratuita con salas de Chaco, Corrientes, Rosario, amistades, música, inteligencia artificial y más.';return layout({siteUrl,title,description,canonical:'/',schema:{'@context':'https://schema.org','@type':'WebSite',name:'Comunidad Chat',url:siteUrl,description,inLanguage:'es-AR'},body:`<main><section class="hero"><div><span class="eyebrow">CHAT ARGENTINO GRATUITO</span><h1>Conversá y conocé gente en salas de Argentina</h1><p>Ingresá desde el celular o la computadora. Elegí una sala, participá de la conversación pública o hablá en privado.</p><div class="actions"><a class="primary" href="/chat">Entrar al chat</a><a class="secondary" href="#salas">Ver las salas</a></div></div><div class="heroCard"><strong>Ahora podés conversar en</strong><ul><li>Chaco y Corrientes</li><li>Rosario</li><li>Amistades y música</li><li>Inteligencia artificial</li></ul></div></section><section id="salas" class="section"><span class="eyebrow">ELEGÍ TU COMUNIDAD</span><h2>Salas disponibles</h2><p class="lead">Cada sala tiene una conversación pública y permite iniciar chats privados con personas conectadas.</p><div class="roomGrid">${cards()}</div></section><section class="features"><article><b>💬</b><h3>Conversación en vivo</h3><p>Mensajes públicos y privados en tiempo real.</p></article><article><b>📱</b><h3>Desde cualquier dispositivo</h3><p>Diseñado para celulares y computadoras.</p></article><article><b>🛡️</b><h3>Comunidad moderada</h3><p>Normas de convivencia y filtros de seguridad.</p></article></section><section id="normas" class="section text"><h2>Un espacio para conversar con respeto</h2><p>No compartas datos personales, contraseñas ni información bancaria. No se permiten amenazas, discriminación, acoso, contenido ilegal ni suplantación de identidad. Los usuarios que incumplan las normas pueden ser expulsados.</p></section></main>`})}
function renderRoom(siteUrl,room){const canonical=`/salas/${room.slug}`;return layout({siteUrl,title:`${room.title} | Comunidad Chat`,description:room.description,canonical,schema:{'@context':'https://schema.org','@type':'WebPage',name:room.title,url:siteUrl+canonical,description:room.description,inLanguage:'es-AR'},body:`<main><section class="roomHero"><div><span class="eyebrow">SALA PÚBLICA</span><h1>${room.title}</h1><p>${room.description}</p><a class="primary" href="/chat?canal=${encodeURIComponent(room.short)}">Entrar a #${room.short}</a><small>Acceso gratuito · No requiere instalar una aplicación</small></div></section><section class="section twoCols"><article><h2>Conocé la sala</h2><p>Esta comunidad reúne a ${room.places}. Podés participar de la conversación general y, si ambas personas están conectadas, iniciar un chat privado.</p><h3>¿Cómo ingresar?</h3><ol><li>Presioná “Entrar a #${room.short}”.</li><li>Elegí un nombre de usuario.</li><li>Comenzá a conversar respetando las normas.</li></ol></article><aside class="rules" id="normas"><h2>Normas básicas</h2><ul><li>Tratá a las demás personas con respeto.</li><li>No publiques información privada.</li><li>No envíes publicidad repetitiva.</li><li>No compartas contenido ilegal u ofensivo.</li><li>Denunciá las conductas peligrosas.</li></ul></aside></section><section id="salas" class="section"><h2>Otras salas</h2><div class="roomGrid compact">${cards()}</div></section></main>`})}
module.exports={rooms,renderHome,renderRoom};
